name: Test dbks new
on:
  workflow_dispatch:
jobs:
  run_terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.3"

      - name: Terraform initialization
        run: terraform init -upgrade

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file="inputs.tfvars"
        
      - name: Terraform Apply
        run: terraform apply -var-file="inputs.tfvars" -auto-approve
