name: Test dbks
on:
  workflow_dispatch:
jobs:
  run_terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.3"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file="inputs.tfvars"

